version: '3.7'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zer0bin
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: frontend/Dockerfile
  #   restart: always
  #   depends_on:
  #     - backend
  #   ports:
  #     - "80:80"

volumes:
  postgres_data:
